git:
  depth: false
sudo: required
language: node_js
node_js:
  - '10'
cache: 
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install --no-progress --frozen-lockfile
stages:
#  - lint
#  - build
  - name: next-version
    if: branch = master AND type = push
jobs:
  include:
    #- stage: lint
    #  script: yarn lint && yarn test && yarn build
    - stage: next-version
      script: skip
      if: branch = master AND type = push
      before_deploy:
        - git config --local user.name "TravisCI"
        - git config --local user.email "frontend@xcritical.software"
        - git fetch --tags --force
        - git remote add origin-master https://${GH_TOKEN}@github.com/xcritical-software/xc-front-presets-test.git > /dev/null 2>&1
        - git tag
      after_deploy:
        - git push origin-master --tags
        - git tag
      deploy:
        provider: script
        script: yarn boltify versions --no-push
        skip_cleanup: true
        on:
          branch: master