git:
  depth: 1
sudo: required
language: node_js
node_js:
  - '10'
cache: 
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install --no-progress
jobs:
  include:
    - stage: build
      if: branch = master AND type = push
      script: yarn build